server:
  port: 8080

spring:
  application:
    name: auth-center-example-app

# 业务系统白名单
example-app:
  security:
    permit-all:
      - /api/hello
      - /auth/login
      - /swagger-ui/**
      - /v3/api-docs/**

# Auth Center（通用鉴权模块）配置
auth-center:
  # NONE | SPRING | REQUIRE_PERM | BOTH
  method-security-mode: BOTH
  #  JWT 相关配置
  jwt:
    # JWT 签发方（iss）
    issuer: "auth-center-demo"
    # 受众
    audience:
      - "example-app"
    # 密钥
    secret: "0123456789abcdef0123456789abcdef"
    access-ttl-seconds: 1800   # access token 有效期（秒）
    refresh-enabled: true # 是否启用 refresh token 机制
    refresh-ttl-seconds: 604800 # refresh token 有效期（秒）
    clock-skew-seconds: 30 # 时间偏移容忍（秒）

